### ISSUE TITLE
Broken recipe createaddition:crude_burning/crude_oil

### ISSUE THREAD

**Issue by JaisDK** [mrh0/createaddition#150]
**Describe the bug**
[22:29:20] [Render thread/ERROR] [minecraft/RecipeManager]: Parsing error loading recipe createaddition:crude_burning/crude_oil
com.google.gson.JsonSyntaxException: Unknown fluid tag 'forge:crude_oil'
	at com.simibubi.create.foundation.fluid.FluidIngredient$FluidTagIngredient.readInternal(FluidIngredient.java:240) ~[create-328085-3419412_mapped_official_1.16.5.jar:mc1.16.5_v0.3.2d] {re:classloading}
	at com.simibubi.create.foundation.fluid.FluidIngredient.deserialize(FluidIngredient.java:130) ~[create-328085-3419412_mapped_official_1.16.5.jar:mc1.16.5_v0.3.2d] {re:classloading}
	at com.mrh0.createaddition.recipe.crude_burning.CrudeBurningRecipeSerializer.readFromJson(CrudeBurningRecipeSerializer.java:41) ~[createaddition-439890-3476770_mapped_official_1.16.5.jar:1.16.5-20210930a] {re:classloading}
	at com.mrh0.createaddition.recipe.crude_burning.CrudeBurningRecipeSerializer.readFromJson(CrudeBurningRecipeSerializer.java:13) ~[createaddition-439890-3476770_mapped_official_1.16.5.jar:1.16.5-20210930a] {re:classloading}
	at com.mrh0.createaddition.recipe.CARecipeSerializer.fromJson(CARecipeSerializer.java:20) ~[createaddition-439890-3476770_mapped_official_1.16.5.jar:1.16.5-20210930a] {re:classloading}
	at net.minecraft.item.crafting.RecipeManager.fromJson(RecipeManager.java:141) ~[forge-1.16.5-36.2.4_mapped_official_1.16.5.jar:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.item.crafting.RecipeManager.apply(RecipeManager.java:61) ~[forge-1.16.5-36.2.4_mapped_official_1.16.5.jar:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.item.crafting.RecipeManager.apply(RecipeManager.java:38) ~[forge-1.16.5-36.2.4_mapped_official_1.16.5.jar:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.resources.ReloadListener.lambda$reload$1(SourceFile:13) ~[forge-1.16.5-36.2.4_mapped_official_1.16.5.jar:?] {re:classloading,re:mixin}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?] {}

**To Reproduce**
Load game

**Additional context**
- Mod version: 1.16.5-20210930a
- Forge version: 1.16.5-36.2.4
- Create version: 1.16.5 v0.3.2d

**Comment by Hypsellis** [comment]
There are more errors in the log, here all the ones that I found.

```
[03:35:06] [Render thread/ERROR]: Parsing error loading recipe createaddition:crude_burning/crude_oil
com.google.gson.JsonSyntaxException: Unknown fluid tag 'forge:crude_oil'
	at com.simibubi.create.foundation.fluid.FluidIngredient$FluidTagIngredient.readInternal(FluidIngredient.java:240) ~[?:mc1.16.5_v0.3.2f]
	at com.simibubi.create.foundation.fluid.FluidIngredient.deserialize(FluidIngredient.java:130) ~[?:mc1.16.5_v0.3.2f]
	at com.mrh0.createaddition.recipe.crude_burning.CrudeBurningRecipeSerializer.readFromJson(CrudeBurningRecipeSerializer.java:41) ~[?:1.16.5-20211023a]
	at com.mrh0.createaddition.recipe.crude_burning.CrudeBurningRecipeSerializer.readFromJson(CrudeBurningRecipeSerializer.java:13) ~[?:1.16.5-20211023a]
	at com.mrh0.createaddition.recipe.CARecipeSerializer.func_199425_a_(CARecipeSerializer.java:20) ~[?:1.16.5-20211023a]
	at net.minecraft.item.crafting.RecipeManager.func_215377_a(RecipeManager.java:141) ~[?:?]
	at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:61) [?:?]
	at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:38) [?:?]
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) [?:?]
	at net.minecraft.client.resources.ReloadListener$$Lambda$15180/1413962017.accept(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) [?:1.8.0_51]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) [?:?]
	at net.minecraft.resources.AsyncReloader$$Lambda$15553/262634098.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at net.minecraft.client.Minecraft.func_238189_a_(Minecraft.java:1863) [?:?]
	at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:1712) [?:?]
	at net.minecraft.client.Minecraft.func_238192_a_(Minecraft.java:1685) [?:?]
	at net.minecraft.client.gui.screen.CreateWorldScreen.func_195352_j(CreateWorldScreen.java:260) [?:?]
	at net.minecraft.client.gui.screen.CreateWorldScreen.lambda$init$11(CreateWorldScreen.java:205) [?:?]
	at net.minecraft.client.gui.screen.CreateWorldScreen$$Lambda$18459/1090290967.onPress(Unknown Source) [?:?]
	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33) [?:?]
	at net.minecraft.client.gui.widget.button.AbstractButton.func_230982_a_(SourceFile:16) [?:?]
	at net.minecraft.client.gui.widget.Widget.func_231044_a_(Widget.java:136) [?:?]
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) [?:?]
	at net.minecraft.client.MouseHelper.func_198033_b(MouseHelper.java:87) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$18162/680364917.run(Unknown Source) [?:?]
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) [?:?]
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) [?:?]
	at net.minecraft.client.MouseHelper.func_228030_c_(MouseHelper.java:181) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$18161/332207984.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) [?:?]
	at net.minecraft.client.MouseHelper.func_228028_b_(MouseHelper.java:180) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$15148/390075275.invoke(Unknown Source) [?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:109) [?:?]
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:305) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:996) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.8.jar:36.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$479/253613492.call(Unknown Source) [forge-1.16.5-36.2.8.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
[03:35:07] [Render thread/ERROR]: Parsing error loading recipe createaddition:crude_burning/creosote
com.google.gson.JsonSyntaxException: Unknown fluid tag 'forge:creosote'
	at com.simibubi.create.foundation.fluid.FluidIngredient$FluidTagIngredient.readInternal(FluidIngredient.java:240) ~[?:mc1.16.5_v0.3.2f]
	at com.simibubi.create.foundation.fluid.FluidIngredient.deserialize(FluidIngredient.java:130) ~[?:mc1.16.5_v0.3.2f]
	at com.mrh0.createaddition.recipe.crude_burning.CrudeBurningRecipeSerializer.readFromJson(CrudeBurningRecipeSerializer.java:41) ~[?:1.16.5-20211023a]
	at com.mrh0.createaddition.recipe.crude_burning.CrudeBurningRecipeSerializer.readFromJson(CrudeBurningRecipeSerializer.java:13) ~[?:1.16.5-20211023a]
	at com.mrh0.createaddition.recipe.CARecipeSerializer.func_199425_a_(CARecipeSerializer.java:20) ~[?:1.16.5-20211023a]
	at net.minecraft.item.crafting.RecipeManager.func_215377_a(RecipeManager.java:141) ~[?:?]
	at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:61) [?:?]
	at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:38) [?:?]
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) [?:?]
	at net.minecraft.client.resources.ReloadListener$$Lambda$15180/1413962017.accept(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) [?:1.8.0_51]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) [?:?]
	at net.minecraft.resources.AsyncReloader$$Lambda$15553/262634098.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at net.minecraft.client.Minecraft.func_238189_a_(Minecraft.java:1863) [?:?]
	at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:1712) [?:?]
	at net.minecraft.client.Minecraft.func_238192_a_(Minecraft.java:1685) [?:?]
	at net.minecraft.client.gui.screen.CreateWorldScreen.func_195352_j(CreateWorldScreen.java:260) [?:?]
	at net.minecraft.client.gui.screen.CreateWorldScreen.lambda$init$11(CreateWorldScreen.java:205) [?:?]
	at net.minecraft.client.gui.screen.CreateWorldScreen$$Lambda$18459/1090290967.onPress(Unknown Source) [?:?]
	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33) [?:?]
	at net.minecraft.client.gui.widget.button.AbstractButton.func_230982_a_(SourceFile:16) [?:?]
	at net.minecraft.client.gui.widget.Widget.func_231044_a_(Widget.java:136) [?:?]
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) [?:?]
	at net.minecraft.client.MouseHelper.func_198033_b(MouseHelper.java:87) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$18162/680364917.run(Unknown Source) [?:?]
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) [?:?]
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) [?:?]
	at net.minecraft.client.MouseHelper.func_228030_c_(MouseHelper.java:181) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$18161/332207984.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) [?:?]
	at net.minecraft.client.MouseHelper.func_228028_b_(MouseHelper.java:180) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$15148/390075275.invoke(Unknown Source) [?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:109) [?:?]
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:305) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:996) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.8.jar:36.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$479/253613492.call(Unknown Source) [forge-1.16.5-36.2.8.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
[03:35:08] [Render thread/ERROR]: Parsing error loading recipe createaddition:compat/tconstruct/pig_iron
com.google.gson.JsonSyntaxException: Unknown item tag 'forge:clay'
	at net.minecraft.item.crafting.Ingredient.func_199803_a(Ingredient.java:223) ~[?:?]
	at net.minecraftforge.common.crafting.VanillaIngredientSerializer.parse(VanillaIngredientSerializer.java:41) ~[?:?]
	at net.minecraftforge.common.crafting.CraftingHelper.getIngredient(CraftingHelper.java:155) ~[?:?]
	at net.minecraft.item.crafting.Ingredient.func_199802_a(Ingredient.java:189) ~[?:?]
	at com.simibubi.create.content.contraptions.processing.ProcessingRecipeSerializer.readFromJson(ProcessingRecipeSerializer.java:72) ~[?:mc1.16.5_v0.3.2f]
	at com.simibubi.create.content.contraptions.processing.ProcessingRecipeSerializer.fromJson(ProcessingRecipeSerializer.java:160) ~[?:mc1.16.5_v0.3.2f]
	at com.simibubi.create.content.contraptions.processing.ProcessingRecipeSerializer.func_199425_a_(ProcessingRecipeSerializer.java:22) ~[?:mc1.16.5_v0.3.2f]
	at net.minecraft.item.crafting.RecipeManager.func_215377_a(RecipeManager.java:141) ~[?:?]
	at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:61) [?:?]
	at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:38) [?:?]
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) [?:?]
	at net.minecraft.client.resources.ReloadListener$$Lambda$15180/1413962017.accept(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) [?:1.8.0_51]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) [?:?]
	at net.minecraft.resources.AsyncReloader$$Lambda$15553/262634098.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at net.minecraft.client.Minecraft.func_238189_a_(Minecraft.java:1863) [?:?]
	at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:1712) [?:?]
	at net.minecraft.client.Minecraft.func_238192_a_(Minecraft.java:1685) [?:?]
	at net.minecraft.client.gui.screen.CreateWorldScreen.func_195352_j(CreateWorldScreen.java:260) [?:?]
	at net.minecraft.client.gui.screen.CreateWorldScreen.lambda$init$11(CreateWorldScreen.java:205) [?:?]
	at net.minecraft.client.gui.screen.CreateWorldScreen$$Lambda$18459/1090290967.onPress(Unknown Source) [?:?]
	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33) [?:?]
	at net.minecraft.client.gui.widget.button.AbstractButton.func_230982_a_(SourceFile:16) [?:?]
	at net.minecraft.client.gui.widget.Widget.func_231044_a_(Widget.java:136) [?:?]
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) [?:?]
	at net.minecraft.client.MouseHelper.func_198033_b(MouseHelper.java:87) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$18162/680364917.run(Unknown Source) [?:?]
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) [?:?]
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) [?:?]
	at net.minecraft.client.MouseHelper.func_228030_c_(MouseHelper.java:181) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$18161/332207984.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) [?:?]
	at net.minecraft.client.MouseHelper.func_228028_b_(MouseHelper.java:180) [?:?]
	at net.minecraft.client.MouseHelper$$Lambda$15148/390075275.invoke(Unknown Source) [?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) [lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:109) [?:?]
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:305) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:996) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.8.jar:36.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$479/253613492.call(Unknown Source) [forge-1.16.5-36.2.8.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
```

**Comment by mrh0** [comment]
Fixed
