### ISSUE TITLE
Cannot create & enter singleplayer worlds

### ISSUE THREAD

**Issue by ZYFDroid** [mrh0/createaddition#270]
**Describe the bug**
Cannot create & enter singleplayer saves.
![image](https://user-images.githubusercontent.com/39429452/175864945-ae0d2e47-0c01-47ed-9c68-e9400ce8cd9b.png)

Logs:
```
[13:06:38] [Render thread/ERROR]: Parsing error loading recipe createaddition:compat/jeed/shocking
com.google.gson.JsonSyntaxException: Invalid or unsupported recipe type 'jeed:effect_provider'
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.18) ~[?:?]
	at net.minecraft.recipe.RecipeManager.method_17875(RecipeManager:124) ~[?:?]
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
	at net.minecraft.recipe.RecipeManager.deserialize(RecipeManager:124) ~[?:?]
	at net.minecraft.recipe.RecipeManager.apply(RecipeManager:54) ~[?:?]
	at net.minecraft.recipe.RecipeManager.apply(RecipeManager:33) ~[?:?]
	at net.minecraft.resource.SinglePreparationResourceReloader.method_18790(SinglePreparationResourceReloader:13) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:69) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:140) ~[?:?]
	at net.minecraft.client.MinecraftClient.method_40183(MinecraftClient:2123) ~[?:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient:1972) ~[?:?]
	at net.minecraft.client.MinecraftClient.method_29609(MinecraftClient:1975) ~[?:?]
	at net.minecraft.client.gui.screen.DatapackFailureScreen.method_29346(DatapackFailureScreen:23) ~[?:?]
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget:40) ~[?:?]
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget:16) ~[?:?]
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget:121) ~[?:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27) ~[?:?]
	at net.minecraft.client.Mouse.method_1611(Mouse:94) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:492) ~[?:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse:94) ~[?:?]
	at net.minecraft.client.Mouse.method_22686(Mouse:165) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:103) ~[?:?]
	at net.minecraft.client.Mouse.method_22684(Mouse:165) ~[?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem:222) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1150) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.6.jar:?]
[13:15:39] [Render thread/INFO]: [STDOUT]: CHARGING createaddition:compat/ae2/charged_certus_quartz net.minecraft.class_1856@1872ac5b 1 CustomEntityItem[charged_certus_quartz_crystal] 10000
[13:15:39] [Render thread/INFO]: Loaded 87 recipes
[13:15:39] [Render thread/INFO]: Closing rrp extshape:standard
[13:15:39] [Render thread/WARN]: Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/fabricmc/fabric/mixin/loot/table/LootSupplierBuilderHooks
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.18) ~[?:?]
	at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:?]
	at net.minecraft.client.MinecraftClient.method_40183(MinecraftClient:2124) ~[?:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient:1972) ~[?:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient:1937) ~[?:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget$Entry.start(WorldListWidget:431) ~[?:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget$Entry.play(WorldListWidget:340) ~[?:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget$Entry.mouseClicked(WorldListWidget:271) ~[?:?]
	at net.minecraft.client.gui.widget.EntryListWidget.mouseClicked(EntryListWidget:359) ~[?:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27) ~[?:?]
	at net.minecraft.client.Mouse.method_1611(Mouse:94) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:492) ~[?:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse:94) ~[?:?]
	at net.minecraft.client.Mouse.method_22686(Mouse:165) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:103) ~[?:?]
	at net.minecraft.client.Mouse.method_22684(Mouse:165) ~[?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem:222) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1150) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.6.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/mixin/loot/table/LootSupplierBuilderHooks
	at com.epherical.croptopia.items.CropLootTableModifier.lambda$init$0(CropLootTableModifier.java:35) ~[Croptopia-1.18.2-FABRIC-2.0.3.jar:?]
	at net.fabricmc.fabric.api.loot.v1.event.LootTableLoadingCallback.lambda$static$0(LootTableLoadingCallback.java:47) ~[fabric-loot-tables-v1-1.1.1+e747827960-259e22a663c5d7ca.jar:?]
	at net.fabricmc.fabric.impl.loot.table.LootTablesV1Init.lambda$onInitialize$1(LootTablesV1Init.java:40) ~[fabric-loot-tables-v1-1.1.1+e747827960-259e22a663c5d7ca.jar:?]
	at net.fabricmc.fabric.api.loot.v2.LootTableEvents.lambda$static$0(LootTableEvents.java:39) ~[fabric-loot-api-v2-1.0.1+e747827960-964fed88d57da80b.jar:?]
	at net.minecraft.loot.LootManager.md800944$lambda$apply$0$0(LootManager:567) ~[?:?]
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:196) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.loot.LootManager.handler$bha000$apply(LootManager:555) ~[?:?]
	at net.minecraft.loot.LootManager.apply(LootManager:59) ~[?:?]
	at net.minecraft.loot.LootManager.apply(LootManager:17) ~[?:?]
	at net.minecraft.resource.SinglePreparationResourceReloader.method_18790(SinglePreparationResourceReloader:13) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:69) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:140) ~[?:?]
	at net.minecraft.client.MinecraftClient.method_40183(MinecraftClient:2123) ~[?:?]
	... 23 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.mixin.loot.table.LootSupplierBuilderHooks
	at com.epherical.croptopia.items.CropLootTableModifier.lambda$init$0(CropLootTableModifier.java:35) ~[Croptopia-1.18.2-FABRIC-2.0.3.jar:?]
	at net.fabricmc.fabric.api.loot.v1.event.LootTableLoadingCallback.lambda$static$0(LootTableLoadingCallback.java:47) ~[fabric-loot-tables-v1-1.1.1+e747827960-259e22a663c5d7ca.jar:?]
	at net.fabricmc.fabric.impl.loot.table.LootTablesV1Init.lambda$onInitialize$1(LootTablesV1Init.java:40) ~[fabric-loot-tables-v1-1.1.1+e747827960-259e22a663c5d7ca.jar:?]
	at net.fabricmc.fabric.api.loot.v2.LootTableEvents.lambda$static$0(LootTableEvents.java:39) ~[fabric-loot-api-v2-1.0.1+e747827960-964fed88d57da80b.jar:?]
	at net.minecraft.loot.LootManager.md800944$lambda$apply$0$0(LootManager:567) ~[?:?]
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:196) ~[guava-31.0.1-jre.jar:?]
	at net.minecraft.loot.LootManager.handler$bha000$apply(LootManager:555) ~[?:?]
	at net.minecraft.loot.LootManager.apply(LootManager:59) ~[?:?]
	at net.minecraft.loot.LootManager.apply(LootManager:17) ~[?:?]
	at net.minecraft.resource.SinglePreparationResourceReloader.method_18790(SinglePreparationResourceReloader:13) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:69) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:140) ~[?:?]
	at net.minecraft.client.MinecraftClient.method_40183(MinecraftClient:2123) ~[?:?]
	... 23 more

```

**To Reproduce**
install mods in the list
```
Adorn-3.5.0+1.18.2-fabric.jar
appleskin-fabric-mc1.18.2-2.4.0.jar
appliedenergistics2-11.0.0.jar
architectury-4.4.68.jar
badpackets-fabric-0.1.2.jar
balm-fabric-3.0.0+0.jar
BetterPingDisplay-Fabric-1.18.2-1.1.1.jar
Botania-1.18.2-433-FABRIC.jar
brrp-0.6.2-1.18.2.jar
cc-restitched-1.100.6.jar
chipped-1.2.jar
cloth-config-6.2.62-fabric.jar
create-mc1.18.2_v0.4.1+631.jar
createaddition-1.18.2-20220621a.jar
Croptopia-1.18.2-FABRIC-2.0.3.jar
extshape-1.5.1-mc1.18.2.jar
fabric-api-0.56.1+1.18.2.jar
fabric-language-kotlin-1.7.4+kotlin.1.6.21.jar
fat-experience-orbs-2.0.0+1.18.1.jar
indium-1.0.3+mc1.18.2.jar
indrev-1.14.0-BETA.jar
InventoryHUD-fabric-[1.18]+-3.4.2.jar
InventoryProfilesNext-fabric-1.18.2-1.5.0.jar
iris-mc1.18.2-1.2.4-build.38.jar
lambdynamiclights-2.1.0+1.17.jar
light-overlay-6.0.5.jar
litematica-fabric-1.18.2-0.11.3.jar
majobroom-1.3.jar
malilib-fabric-1.18.2-0.12.1.jar
modmenu-3.2.2.jar
MTR-fabric-1.18.2-3.0.1.jar
notenoughcrashes-4.1.6+1.18.2-fabric.jar
owo-lib-0.7.2+1.18.jar
Patchouli-1.18.2-69-FABRIC.jar
reeses_sodium_options-mc1.18.2-1.4.2.jar
RoughlyEnoughItems-8.2.470.jar
sodium-extra-0.4.4+mc1.18.2-build.39.jar
sodium-fabric-mc1.18.2-0.4.1+build.15.jar
spectrum-1.3.3-1.18.2-midgame18-trinkets-brewing.jar
TechReborn-5.2.0.jar
torohealth-1.18-fabric-2.jar
tps-hud-1.2-SNAPSHOT.jar
trinkets-3.3.1.jar
worldedit-mod-7.2.10.jar
wthit-fabric-4.10.3.jar
XaerosWorldMap_1.22.0_Fabric_1.18.2.jar
Xaeros_Minimap_22.8.2_Fabric_1.18.2.jar
```

create or enter a singleplayer world

**Additional context**
- Mod version: 1.18.2-20220621
- Fabric version: 0.14.6
- Create version: 1.18.2_v0.4.1_631

**Comment by ZYFDroid** [comment]
use old version (20220525) works well
