### ISSUE TITLE
Crash when place or ponder on electric motor

### ISSUE THREAD

**Issue by johalun** [mrh0/createaddition#341]
**Describe the bug**
I crafted a electric motor and when I pondered on the item in my inventory the client crashed. After placing it in my world the server crashed and crashes on every start now. I had to disable the mod to start the server again.

**To Reproduce**
Craft electric motor with mechanical crafter. Place in world (possibly next to tech reborn fiber cable).

**Additional context**
- Mod version: createaddition+1.18.2-20220911a
- Fabric version: 0.14.9
- Create version: create-1.18.2-0.5.0c-708
- Mod pack: Valhelsia Enhanced Vanilla 1.4.1 with upgraded fabric to 0.14.9 (comes with 0.14.8)

Crash log
```
[10:11:34] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [krypton]) disables it and children
	at appeng.hooks.ticking.TickHandler.readyBlockEntities(TickHandler.java:369) ~[appliedenergistics2-11.1.5.jar:?]
	at appeng.hooks.ticking.TickHandler.onServerLevelTickEnd(TickHandler.java:247) ~[appliedenergistics2-11.1.5.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$6(ServerTickEvents.java:108) ~[fabric-lifecycle-events-v1-2.1.0+cc71601c60-e0ce7e13c32befa7.jar:?]
	at net.minecraft.server.world.ServerWorld.handler$bph000$endWorldTick(ServerWorld:7166) ~[?:?]
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:374) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:907) ~[server-intermediary.jar:?]
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:322) ~[?:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:851) ~[server-intermediary.jar:?]
[10:11:46] [Worker-Main-3/INFO]: Resource levelz:entity/unlock_cow.json was not loaded cause it already existed
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:697) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[10:04:51] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Readying AE2 block entity
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:911) ~[server-intermediary.jar:?]
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:322) ~[?:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:851) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:697) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.class_5250 com.simibubi.create.foundation.utility.Lang.translateDirect(java.lang.String, java.lang.Object[])'
	at com.mrh0.createaddition.blocks.electric_motor.ElectricMotorTileEntity.addBehaviours(ElectricMotorTileEntity.java:75) ~[createaddition+1.18.2-20220911a.jar:?]
	at com.simibubi.create.foundation.tileEntity.SmartTileEntity.<init>(SmartTileEntity.java:43) ~[create-1.18.2-0.5.0c-708.jar:?]
	at com.simibubi.create.content.contraptions.base.KineticTileEntity.<init>(KineticTileEntity.java:71) ~[create-1.18.2-0.5.0c-708.jar:?]
	at com.simibubi.create.content.contraptions.base.GeneratingKineticTileEntity.<init>(GeneratingKineticTileEntity.java:23) ~[create-1.18.2-0.5.0c-708.jar:?]
	at com.mrh0.createaddition.blocks.electric_motor.ElectricMotorTileEntity.<init>(ElectricMotorTileEntity.java:59) ~[createaddition+1.18.2-20220911a.jar:?]
	at com.tterrag.registrate.builders.BlockEntityBuilder.lambda$createEntry$2(BlockEntityBuilder.java:132) ~[registrate-fabric-MC1.18.2-1.1.3-78e8b485aa276df7.jar:?]
	at net.minecraft.block.entity.BlockEntityType.instantiate(BlockEntityType:84) ~[?:?]
	at com.tterrag.registrate.util.entry.BlockEntityEntry.create(BlockEntityEntry.java:28) ~[registrate-fabric-MC1.18.2-1.1.3-78e8b485aa276df7.jar:?]
	at com.mrh0.createaddition.blocks.electric_motor.ElectricMotorBlock.createBlockEntity(ElectricMotorBlock.java:62) ~[createaddition+1.18.2-20220911a.jar:?]
	at net.minecraft.world.chunk.WorldChunk.createBlockEntity(WorldChunk:292) ~[?:?]
	at net.minecraft.world.chunk.WorldChunk.getBlockEntity(WorldChunk:315) ~[?:?]
	at net.minecraft.world.World.getBlockEntity(World:533) ~[?:?]
	at appeng.api.networking.GridHelper.getNodeHost(GridHelper.java:133) ~[appliedenergistics2-11.1.5.jar:?]
	at appeng.api.networking.GridHelper.getExposedNode(GridHelper.java:150) ~[appliedenergistics2-11.1.5.jar:?]
	at appeng.me.InWorldGridNode.findInWorldConnections(InWorldGridNode.java:67) ~[appliedenergistics2-11.1.5.jar:?]
	at appeng.me.GridNode.updateState(GridNode.java:227) ~[appliedenergistics2-11.1.5.jar:?]
	at appeng.me.GridNode.markReady(GridNode.java:374) ~[appliedenergistics2-11.1.5.jar:?]
	at appeng.me.ManagedGridNode.createNode(ManagedGridNode.java:174) ~[appliedenergistics2-11.1.5.jar:?]
	at appeng.me.ManagedGridNode.create(ManagedGridNode.java:160) ~[appliedenergistics2-11.1.5.jar:?]
	at appeng.parts.AEBasePart.addToWorld(AEBasePart.java:203) ~[appliedenergistics2-11.1.5.jar:?]
	at appeng.parts.CableBusContainer.addToWorld(CableBusContainer.java:517) ~[appliedenergistics2-11.1.5.jar:?]
	at appeng.blockentity.networking.CableBusBlockEntity.onReady(CableBusBlockEntity.java:174) ~[appliedenergistics2-11.1.5.jar:?]
	at appeng.hooks.ticking.ServerBlockEntityRepo$FirstTickInfo.callInit(ServerBlockEntityRepo.java:44) ~[appliedenergistics2-11.1.5.jar:?]
	at appeng.hooks.ticking.TickHandler.readyBlockEntities(TickHandler.java:367) ~[appliedenergistics2-11.1.5.jar:?]
	at appeng.hooks.ticking.TickHandler.onServerLevelTickEnd(TickHandler.java:247) ~[appliedenergistics2-11.1.5.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$6(ServerTickEvents.java:108) ~[fabric-lifecycle-events-v1-2.1.0+cc71601c60-e0ce7e13c32befa7.jar:?]
	at net.minecraft.server.world.ServerWorld.handler$bph000$endWorldTick(ServerWorld:7166) ~[?:?]
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:374) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:907) ~[server-intermediary.jar:?]
```

**Comment by nebulazorua** [comment]
Also happens for me aswell, with my own set of mods
[crash-2022-09-13_06.54.20-client.txt](https://github.com/mrh0/createaddition/files/9552269/crash-2022-09-13_06.54.20-client.txt)
k

**Comment by mrh0** [comment]
Update the mod
