### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by zenperfect** [mrh0/createaddition#394]
Crashed multiple times while attempting to start 1.19.2 Fabric client. All crashed with the same error. Crash log is attached, top of the error block:

---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 2022-11-26 18:24:00
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'createaddition'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchFieldError: REGISTRATE
	at com.mrh0.createaddition.index.CABlocks.register(CABlocks.java:133)
	at com.mrh0.createaddition.CreateAddition.onInitialize(CreateAddition.java:55)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more
[crash-2022-11-26_18.24.00-client.txt](https://github.com/mrh0/createaddition/files/10096709/crash-2022-11-26_18.24.00-client.txt)

**Comment by mrh0** [comment]
old version, update
