### ISSUE TITLE
crash when hovering seed oil bucket in creative inventory and REI

### ISSUE THREAD

**Issue by WABUHA** [mrh0/createaddition#403]
crash when howering cursor on seed oil, and after adding mod rei search dont work

I use the AOF6 modpack

logs:
[03:44:19] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:890) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1177) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.10.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.simibubi.create.content.AllSections.getTooltipPalette()" because "module" is null
	at com.simibubi.create.foundation.item.TooltipHelper.buildToolTip(TooltipHelper.java:273) ~[create-fabric-0.5.0g-796+1.19.2.jar:?]
	at com.simibubi.create.foundation.item.TooltipHelper.findTooltip(TooltipHelper.java:264) ~[create-fabric-0.5.0g-796+1.19.2.jar:?]
	at com.simibubi.create.foundation.item.TooltipHelper.hasTooltip(TooltipHelper.java:247) ~[create-fabric-0.5.0g-796+1.19.2.jar:?]
	at com.simibubi.create.events.ClientEvents.addToItemTooltip(ClientEvents.java:278) ~[create-fabric-0.5.0g-796+1.19.2.jar:?]
	at net.fabricmc.fabric.api.client.item.v1.ItemTooltipCallback.lambda$static$0(ItemTooltipCallback.java:37) ~[fabric-item-api-v1-1.6.1+fa140d5990-60a39b20c851ca57.jar:?]
	at net.minecraft.class_1799.handler$djm000$getTooltip(class_1799.java:5662) ~[client-intermediary.jar:?]
	at net.minecraft.class_1799.method_7950(class_1799.java:835) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25408(class_437.java:181) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25409(class_437.java:168) ~[client-intermediary.jar:?]
	at net.minecraft.class_481.method_25409(class_481.java:731) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.method_2380(class_465.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.class_481.method_25394(class_481.java:692) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:881) ~[client-intermediary.jar:?]
	... 7 more

- Mod version:[1.19.2-20221128a]
- Fabric version: 1.19.2
- Create version:0.5.0g-796

**Comment by creepypasha** [comment]
[crash-2022-12-04_03.44.19-client.txt](https://github.com/mrh0/createaddition/files/10147671/crash-2022-12-04_03.44.19-client.txt)

**Comment by StarskyXIII** [comment]
Try to remove language file which you are applied.
Or just remove these strings
```"item.createaddition.seed_oil_bucket.tooltip": "SEED_OIL_BUCKET",```
```"item.createaddition.seed_oil_bucket.tooltip.summary": "A simple _flammable liquid_.",```

**Comment by WABUHA** [comment]
> Try to remove language file which you are applied. Or just remove these strings in the json file of your language. `"item.createaddition.seed_oil_bucket.tooltip": "SEED_OIL_BUCKET",` `"item.createaddition.seed_oil_bucket.tooltip.summary": "A simple _flammable liquid_.",`

where is locate lang files?(cant find)

**Comment by StarskyXIII** [comment]
createaddition+1.19.2-1.19.2-20221218a.jar\assets\createaddition\lang\

**Comment by WABUHA** [comment]
> createaddition+1.19.2-1.19.2-20221218a.jar\assets\createaddition\lang\

it works, thanks!

**Comment by WABUHA** [comment]
> createaddition+1.19.2-1.19.2-20221218a.jar\assets\createaddition\lang\

for now this dont helps
[crash-2023-02-02_08.33.11-client.txt](https://github.com/mrh0/createaddition/files/10565789/crash-2023-02-02_08.33.11-client.txt)
