### ISSUE TITLE
Breaking or placing Blaze Burners crashes the game

### ISSUE THREAD

**Issue by megargayu** [mrh0/createaddition#507]
**Describe the bug**
When I try to break or place a blaze burner under a tank attached to a running steam engine, the game immediately crashes - however, it's perfectly fine if I break the steam engine, do my modifications to the blaze burners, and then place the steam engine back onto the tank.

**To Reproduce**
1. Create a steam engine setup (tank + water + steam engine with shaft + blaze burners underneath the water tank)
2. While the steam engine is running, break one of the blaze burners underneath
3. The game should crash.

**Full Crash Report (Including Versions):**
```
---- Minecraft Crash Report ----
// You're mean.

Time: 2023-03-08 16:26:37
Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot get property class_2754{name=blaze, clazz=class com.simibubi.create.content.contraptions.processing.burner.BlazeBurnerBlock$HeatLevel, values=[NONE, SMOULDERING, FADING, KINDLED, SEETHING]} as it does not exist in Block{minecraft:air}
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at com.mrh0.createaddition.CreateAddition.lambda$onInitialize$0(CreateAddition.java:41)
	at com.simibubi.create.content.contraptions.fluids.tank.BoilerHeaters.getActiveHeat(BoilerHeaters.java:46)
	at com.simibubi.create.content.contraptions.fluids.tank.BoilerData.updateTemperature(BoilerData.java:343)
	at com.simibubi.create.content.contraptions.fluids.tank.BoilerData.tick(BoilerData.java:84)
	at com.simibubi.create.content.contraptions.fluids.tank.FluidTankTileEntity.tick(FluidTankTileEntity.java:112)
	at com.simibubi.create.foundation.tileEntity.SmartTileEntityTicker.tick(SmartTileEntityTicker.java:15)
	at net.minecraft.class_2818$class_5563.redirect$zmj000$checkProcessBEs(class_2818.java:784)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
	at net.minecraft.class_1937.method_18471(class_1937.java:456)
	at net.minecraft.class_3218.method_18765(class_3218.java:376)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.handler$zmg000$modifiedRunLoop(MinecraftServer.java:3885)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at com.mrh0.createaddition.CreateAddition.lambda$onInitialize$0(CreateAddition.java:41)
	at com.simibubi.create.content.contraptions.fluids.tank.BoilerHeaters.getActiveHeat(BoilerHeaters.java:46)
	at com.simibubi.create.content.contraptions.fluids.tank.BoilerData.updateTemperature(BoilerData.java:343)
	at com.simibubi.create.content.contraptions.fluids.tank.BoilerData.tick(BoilerData.java:84)
	at com.simibubi.create.content.contraptions.fluids.tank.FluidTankTileEntity.tick(FluidTankTileEntity.java:112)
	at com.simibubi.create.foundation.tileEntity.SmartTileEntityTicker.tick(SmartTileEntityTicker.java:15)
	at net.minecraft.class_2818$class_5563.redirect$zmj000$checkProcessBEs(class_2818.java:784)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
	at net.minecraft.class_1937.method_18471(class_1937.java:456)
	at net.minecraft.class_3218.method_18765(class_3218.java:376)

-- Block entity being ticked --
Details:
	Name: create:fluid_tank // com.simibubi.create.content.contraptions.fluids.tank.FluidTankTileEntity
	Block: Block{create:fluid_tank}[bottom=true,light_level=0,shape=plain,top=false]
	Block location: World: (-31,57,-6), Section: (at 1,9,10 in -2,3,-1; chunk contains blocks -32,-64,-16 to -17,319,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Block: Block{create:fluid_tank}[bottom=true,light_level=0,shape=plain,top=false]
	Block location: World: (-31,57,-6), Section: (at 1,9,10 in -2,3,-1; chunk contains blocks -32,-64,-16 to -17,319,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
	at net.minecraft.class_1937.method_18471(class_1937.java:456)
	at net.minecraft.class_3218.method_18765(class_3218.java:376)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.handler$zmg000$modifiedRunLoop(MinecraftServer.java:3885)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Ayushisgr8'/6, l='ServerLevel[cake factory]', x=-29.72, y=56.00, z=-2.64]]
	Chunk stats: 3481
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,56,0), Section: (at 0,8,0 in 0,3,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1893776 game time, 6000 day time
	Level name: cake factory
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.handler$zmg000$modifiedRunLoop(MinecraftServer.java:3885)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 18.0.1.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 581362560 bytes (554 MiB) / 1935671296 bytes (1846 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
	Identifier: Intel64 Family 6 Model 141 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9a60
	Graphics card #0 versionInfo: DriverVersion=30.0.101.1404
	Graphics card #1 name: NVIDIA GeForce RTX 3050 Ti Laptop GPU
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x25a0
	Graphics card #1 versionInfo: DriverVersion=31.0.15.2737
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 26855.82
	Virtual memory used (MB): 17191.75
	Swap memory total (MB): 10752.00
	Swap memory used (MB): 368.86
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Fabric Mods: 
		appleskin: AppleSkin 2.4.1+mc1.19
		architectury: Architectury 6.3.56
		badpackets: Bad Packets 0.2.1
		carpet: Carpet Mod 1.4.84
		carpet-extra: Carpet Extra 1.4.84
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		create: Create 0.5.0g-796+1.19.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			fake-player-api: Fake Player API 0.5.0
			flywheel: Flywheel 0.6.8-1
			forgeconfigapiport: Forge Config API Port 4.2.6
				com_electronwill_night-config_core: core 3.6.5
				com_electronwill_night-config_toml: toml 3.6.5
			milk: Milk Lib 1.0.51
				dripstone_fluid_lib: Dripstone Fluid Lib 2.0.1
			noindium: No Indium? 1.1.0+1.19
			porting_lib: Porting Lib 2.1.623+1.19.2
				forge_tags: Porting Lib Tags 3.0
				porting_lib_base: Porting Lib Base 2.1.623+1.19.2
					com_github_llamalad7_mixinextras: MixinExtras 0.1.1
					mm: Manningham Mills 2.3
					serialization_hooks: Serialization Hooks 0.3.26
				porting_lib_entity: Porting Lib Entity 2.1.623+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.623+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.623+1.19.2
				porting_lib_models: Porting Lib Models 2.1.623+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.623+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.1.623+1.19.2
					porting_lib_model_loader: Porting Lib Model Loader 2.1.623+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.1.623+1.19.2
					porting_lib_extensions: Porting Lib Extensions 2.1.623+1.19.2
						porting_lib_accessors: Porting Lib Accessors 2.1.623+1.19.2
						porting_lib_attributes: Porting Lib Attributes 2.1.623+1.19.2
							porting_lib_constants: Porting Lib Constants 2.1.623+1.19.2
						porting_lib_common: Porting Lib Common 2.1.623+1.19.2
			reach-entity-attributes: Reach Entity Attributes 2.3.0
			registrate-fabric: Registrate for Fabric 1.1.44-MC1.19.2
		createaddition: Create Crafts & Additions ${version}
			team_reborn_energy: Energy 2.2.0
		dynamicfps: Dynamic FPS 2.2.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		enhancedblockentities: Enhanced Block Entities 0.7.2+1.19.2
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
			spruceui: SpruceUI 4.0.0+1.19
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		fabric-api: Fabric API 0.68.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.13+0d0f210290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.12+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.20+0d0f210290
			fabric-block-api-v1: Fabric Block API (v1) 1.0.1+12bfe4ea90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.22+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.3+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.13+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.9+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.30+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.38+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.3+6064db2a90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.3+93d8cb8290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.7+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.2+ad31814d90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.33+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.2+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.31+6eb9a2a190
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.31+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.23+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.6.1+fa140d5990
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.35+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.23+aaaf9d3390
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.21+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.2+9244241690
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.9+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.12+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.5+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.20+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.19+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.8+3b1d070f90
			fabric-networking-v0: Fabric Networking (v0) 0.3.25+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.2+06e0e25190
			fabric-particles-v1: Fabric Particles (v1) 1.0.12+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.29+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.1.0+e7aeff4590
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.17+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.22+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.17+0d0f210290
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.9+c6af733c90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.25+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.1+73145abb90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.1+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.1+0d0f210290
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.29+0d0f210290
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.4+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.1+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.22+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.3+9d081d6490
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.2+42d99c3290
		fabric-language-kotlin: Fabric Language Kotlin 1.8.7+kotlin.1.7.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.11
		ferritecore: FerriteCore 5.0.3
		indium: Indium 1.0.9+mc1.19.2
		iris: Iris 1.5.0
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre8
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: Java HotSpot(TM) 64-Bit Server VM 18
		jei: Just Enough Items 11.5.2.1007
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.10.2
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.1.1
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		starlight: Starlight 1.1.1+fabric.ae22326
		wthit: wthit 5.14.0
		xaerominimapfair: Xaero's Minimap 22.16.3
		xaeroworldmap: Xaero's World Map 1.28.8
		yet-another-config-lib: YetAnotherConfigLib 1.7.1
		zoomify: Zoomify 2.8.0
			dev_isxander_settxi_settxi-core: settxi-core 2.10.3
			dev_isxander_settxi_settxi-gui: settxi-gui 2.10.3
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.3
			settxi-gui-yacl: Settxi Gui (YetAnotherConfigLib) 2.10.3
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Flywheel Backend: GL33 Instanced Arrays
	Server Running: true
	Player Count: 1 / 8; [class_3222['Ayushisgr8'/6, l='ServerLevel[cake factory]', x=-29.72, y=56.00, z=-2.64]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: 1.19.2
```

**Comment by megargayu** [comment]
Nevermind, I just updated to the latest version (which I realized I forgot to do) and it seems the bug was already fixed.
