### ISSUE TITLE
Game Crashes when manually emptying lava-filled Liquid Blaze Burner with a bucket.

### ISSUE THREAD

**Issue by psilocke** [mrh0/createaddition#508]
**Describe the bug**
After right clicking with an empty bucket on the Liquid Blaze Burner full of lava, the game crashes to desktop.

**To Reproduce**
1. Fill Liquid Blaze Burner with lava.
2. Use empty bucket on liquid blaze burner.
3. Game crashes.

**Additional context**
- Mod version: 1.18.2-20230211a
- Fabric version: 0.14.14
- Create version: 0.5.0g-792+1.18.2

**Comment by psilocke** [comment]
After further testing, it seems to happen with a number of items and conditions. Attempting to feed the fluid blaze burner or interact with it cogs, pipes, or fluid containers also results in a crash.

**Comment by kirbyquerby** [comment]
I've had this same issue. The exception thrown before the crash is:
```
java.lang.NoClassDefFoundError: io/github/fabricators_of_create/porting_lib/fake_players/FakePlayer
	at com.mrh0.createaddition.blocks.liquid_blaze_burner.LiquidBlazeBurner.method_9534(LiquidBlazeBurner.java:125) ~[createaddition-fabric+1.18.2-20230211a.jar:?]
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:939) ~[client-intermediary.jar:?]
	at net.minecraft.class_636.method_2896(class_636.java:320) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1583(class_310.java:1659) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1508(class_310.java:1912) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1739) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1091) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.14.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
Caused by: java.lang.ClassNotFoundException: io.github.fabricators_of_create.porting_lib.fake_players.FakePlayer
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.14.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 15 more
```

The main issue being `Caused by: java.lang.ClassNotFoundException: io.github.fabricators_of_create.porting_lib.fake_players.FakePlayer`

I was able to fix the issue in a local build (on the `fabric-1.18.2` branch) by adding the porting lib dependency to the build.gradle:
```gradle
modImplementation(include("io.github.fabricators_of_create:Porting-Lib:1.2.869-beta+1.18.2"))
```
