### ISSUE TITLE
when calling from CC: Tweaked to change/get the speed of rotation_speed_controller via createaddition:digital_adapter, an error prevents the action from being performed da.setTargetSpeed("top", 64) and local speed = da.getTargetSpeed("top")

### ISSUE THREAD

**Issue by Damir00109** [mrh0/createaddition#835]
**Describe the error**
Unable to change the speed controller speed

**Reproduce**
1) Install an advanced PC, connect a digital adapter, install the speed controller on it, and run the code on the PC
1.1)
local da = periferic.wrap("left")
da.setTargetSpeed("top", 64)

or

1.2)
local da = periferic.wrap("left")
local speed = da.getTargetSpeed("top")

**Additional context**
- createaddition version 1.2.4:
- Minecraft 1.20.1 with Fabric Loader 0.16.3:
- create 0.5.1-f-build.1417+mc1.20.1:
- computercraft 1.112.0 or computercraft 1.113.0

logs

[16:27:30] [Server thread/ERROR]: Error running task java.lang.ClassCastException: class com.simibubi.create.content.kinetics.speedController.SpeedControllerBlockEntity cannot be cast to class com.mrh0.createaddition.blocks.digital_adapter.ISpeedControllerAdapter (com.simibubi.create.content.kinetics. speedController.SpeedControllerBlockEntity and com.mrh0.createaddition.blocks.digital_adapter.ISpeedControllerAdapter are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @5f2108b5) at com.mrh0.createaddition.blocks.digital_adapter.DigitalAdapterBlockEntity.getTargetSpeed(DigitalAdapterBlockEntity.java:136) ~[createaddition-fabric+1.20.1-1.2.4.jar:?] at com.mrh0.createaddition.compat.computercraft.DigitalAdapterPeripheral.getTargetSpe ed(DigitalAdapterPeripheral.java:102) ~[createaddition-fabric+1.20.1-1.2.4.jar:?] at dan200.computercraft.core.asm.PeripheralMethodSupplier.lambda$static$0(PeripheralMethodSupplier.java:28) ~[cc-tweaked-1.20.1-fabric-1.112.0.jar:?] at dan200.computercraft.core.asm.PeripheralMethodSupplier.lambda$static$2(PeripheralMethodSupplier.java:35) ~[cc-tweaked-1.20.1-fabric-1.112.0.jar:?] at dan200. computercraft.api.lua.TaskCallback.execute(TaskCallback.java:30) ~[cc-tweaked-1.20.1-fabric-1.112.0.jar:?] at dan200.computercraft.core.computer.GuardedLuaContext.lambda$issueMainThreadTask$0(GuardedLuaContext.java:45) ~[cc-tweaked-1.20.1-fabric-1.112.0.jar:?] at dan200.computercraft.core.computer.LuaContext.lambda$issueMainThreadTask$0(LuaContext .java:29) ~[cc-tweaked-1.20.1-fabric-1.112.0.jar:?] at dan200.computercraft.core.computer.mainthread.MainThreadExecutor.execute(MainThreadExecutor.java:138) ~[cc-tweaked-1.20.1-fabric-1.112.0.jar:?] at dan200.computercraft.core.computer.mainthread.MainThread.tick(MainThread.java:139) ~[cc-tweaked-1.20.1-fabric-1.112.0.jar:?] at dan200.computercraft.shared.computer. core.ServerContext.tick(ServerContext.java:154) ~[cc-tweaked-1.20.1-fabric-1.112.0.jar:?] at dan200.computercraft.shared.CommonHooks.onServerTickStart(CommonHooks.java:49) ~[cc-tweaked-1.20.1-fabric-1.112.0.jar:?] at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$0(ServerTickEvents.java:34) ~[fabric-lifecycle-events-v1-2.2.2+1802ada577-15099 849194dcb7e.jar:?] at net.minecraft.server.MinecraftServer.handler$bmd000$fabric-lifecycle-events-v1$onStartTick(MinecraftServer.java:4357) ~[server-intermediary.jar:?] at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?] at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?] at net.minecraft.server.MinecraftServer.method _29739(MinecraftServer.java:265) ~[server-intermediary.jar:?] at java.lang.Thread.run(Thread.java:1570) ~[?:?]

**Comment by Player1mene** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by skippyall** [comment]
This seems to be a mixin error. Could you please provide the full log?

**Comment by Damir00109** [comment]
[latest.log](https://github.com/user-attachments/files/17530809/latest.log)

**Comment by skippyall** [comment]
The mixins are not registered in fabric.mod.json. I might make a pull request for this
