### ISSUE TITLE
Crash and corrupted save with moving accumulators

### ISSUE THREAD

**Issue by Trabyzonde** [mrh0/createaddition#840]
**Describe the bug**
After moving some accumulators in multiblock (2x2x1, like tanks) with a rope pulley, the game crashed and it was impossible to go back on the map (the game keep crashing). To get back the map, we had to delete all the entities files in the save file. Then, I proced to test on single player map some test to identify the issue and it comes from accumulators imo.

**To Reproduce**
Steps to reproduce the behavior: -place accumulators in configuration 2x2x1 (Lxlxh) (empty or not) and not connected to anything else form other mod
-push one block with a piston from vanilla or create
-crash

**Additional context**
- Mod version: 1.2.4e
- Forge version: 47.3.0
- Create version: 0.5.1.h
I was not able to get crash file, sorry but curseforge did not open it every time, idk
But btw the addon is really great !

**Comment by Trabyzonde** [comment]
I found the crash log using Neruina mod and reproducing the crash :
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate$StructureBlockInfo.f_74677_()" because "prevControllerInfo" is null
	at TRANSFORMER/create@0.5.1.h/com.simibubi.create.content.contraptions.Contraption.lambda$translateMultiblockControllers$21(Contraption.java:1210)
	at MC-BOOTSTRAP/com.google.common@31.1-jre/com.google.common.collect.Maps$KeySet.lambda$forEach$0(Maps.java:4031)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at MC-BOOTSTRAP/com.google.common@31.1-jre/com.google.common.collect.Maps$KeySet.forEach(Maps.java:4031)
	at TRANSFORMER/create@0.5.1.h/com.simibubi.create.content.contraptions.Contraption.translateMultiblockControllers(Contraption.java:1191)
	at TRANSFORMER/create@0.5.1.h/com.simibubi.create.content.contraptions.Contraption.addBlocksToWorld(Contraption.java:1074)
	at TRANSFORMER/create@0.5.1.h/com.simibubi.create.content.contraptions.AbstractContraptionEntity.disassemble(AbstractContraptionEntity.java:668)
	at TRANSFORMER/create@0.5.1.h/com.simibubi.create.content.contraptions.piston.MechanicalPistonBlockEntity.disassemble(MechanicalPistonBlockEntity.java:104)
	at TRANSFORMER/create@0.5.1.h/com.simibubi.create.content.contraptions.piston.LinearActuatorBlockEntity.tryDisassemble(LinearActuatorBlockEntity.java:296)
	at TRANSFORMER/create@0.5.1.h/com.simibubi.create.content.contraptions.piston.LinearActuatorBlockEntity.tick(LinearActuatorBlockEntity.java:157)
	at TRANSFORMER/create@0.5.1.h/com.simibubi.create.foundation.blockEntity.SmartBlockEntityTicker.m_155252_(SmartBlockEntityTicker.java:15)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.mixinextras$bridge$m_155252_$7(LevelChunk.java)
	at TRANSFORMER/neruina@2.1.2/com.bawnorton.neruina.handler.TickHandler.safelyTickBlockEntity(TickHandler.java:169)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.wrapOperation$zfd000$catchTickingBlockEntity$notTheCauseOfTickLag(LevelChunk.java:815)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:689)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:782)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.m_46463_(Level.java:468)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:351)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by mrh0** [comment]
It's an issue on Creates side, either downgrade to Create 0.5.1.g or wait for Create 0.5.1.i
