### ISSUE TITLE
Errors when starting and shutting down the server

### ISSUE THREAD

**Issue by swe3per** [mrh0/createaddition#846]
**Describe the bug**
Errors when starting and shutting down the server：
[latest.log](https://github.com/user-attachments/files/17415313/latest.log)
```
[15:34:14] [Worker-Main-1/WARN]: Your custom createaddition:charging/exposed_cut_copper recipe (createaddition:charging/exposed_cut_copper) specified a duration. Durations have no impact on this type of recipe.
[15:34:14] [Worker-Main-1/WARN]: Your custom createaddition:rolling/electrum_ingot recipe (createaddition:rolling/electrum_ingot) specified a duration. Durations have no impact on this type of recipe.
[15:34:14] [Worker-Main-1/WARN]: Your custom createaddition:charging/exposed_cut_copper_slab recipe (createaddition:charging/exposed_cut_copper_slab) specified a duration. Durations have no impact on this type of recipe.
[15:34:14] [Worker-Main-1/WARN]: Your custom createaddition:charging/weathered_copper_shingles recipe (createaddition:charging/weathered_copper_shingles) specified a duration. Durations have no impact on this type of recipe.
[15:34:14] [Worker-Main-1/WARN]: Your custom createaddition:charging/weathered_copper_shingle_stairs recipe (createaddition:charging/weathered_copper_shingle_stairs) specified a duration. Durations have no impact on this type of recipe.
[15:34:14] [Worker-Main-1/WARN]: Your custom createaddition:charging/exposed_copper recipe (createaddition:charging/exposed_copper) specified a duration. Durations have no impact on this type of recipe.
[15:34:14] [Worker-Main-1/ERROR]: Parsing error loading recipe createaddition:compat/immersiveengineering/item_application/reinforced_blast_brick
com.google.gson.JsonSyntaxException: Unknown item 'immersiveengineering:blastbrick'
	at net.minecraft.class_1869.method_17878(class_1869.java:272) ~[server-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_1869.method_8155(class_1869.java:272) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8107(class_1856.java:160) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_52177(class_1856.java:135) ~[server-intermediary.jar:?]
	at com.simibubi.create.content.processing.recipe.ProcessingRecipeSerializer.readFromJson(ProcessingRecipeSerializer.java:66) ~[create-fabric-0.5.1-f-build.1417+mc1.20.1.jar:?]
	at com.simibubi.create.content.processing.recipe.ProcessingRecipeSerializer.fromJson(ProcessingRecipeSerializer.java:154) ~[create-fabric-0.5.1-f-build.1417+mc1.20.1.jar:?]
	at com.simibubi.create.content.processing.recipe.ProcessingRecipeSerializer.method_8121(ProcessingRecipeSerializer.java:21) ~[create-fabric-0.5.1-f-build.1417+mc1.20.1.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[server-intermediary.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:68) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[server-intermediary.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:68) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[server-intermediary.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:68) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179) ~[?:?]
	at net.minecraft.class_4014$1.method_18374(class_4014.java:51) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[server-intermediary.jar:?]
	at net.minecraft.class_4014$1.method_18352(class_4014.java:48) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
[15:34:14] [Worker-Main-1/WARN]: Your custom createaddition:rolling/brass_ingot recipe (createaddition:rolling/brass_ingot) specified a duration. Durations have no impact on this type of recipe.
[15:34:14] [Worker-Main-1/WARN]: Your custom createaddition:charging/copper_shingle_stairs recipe (createaddition:charging/copper_shingle_stairs) specified a duration. Durations have no impact on this type of recipe.
[15:34:14] [Worker-Main-1/WARN]: Your custom createaddition:rolling/iron_ingot recipe (createaddition:rolling/iron_ingot) specified a duration. Durations have no impact on this type of recipe.
[15:34:14] [Worker-Main-1/WARN]: Your custom createaddition:charging/copper_shingles recipe (createaddition:charging/copper_shingles) specified a duration. Durations have no impact on this type of recipe.
[15:34:14] [Worker-Main-1/WARN]: Your custom createaddition:charging/copper_block recipe (createaddition:charging/copper_block) specified a duration. Durations have no impact on this type of recipe.
[15:34:14] [Worker-Main-1/WARN]: Your custom createaddition:rolling/copper_ingot recipe (createaddition:rolling/copper_ingot) specified a duration. Durations have no impact on this type of recipe.
[15:34:14] [Worker-Main-1/WARN]: Your custom createaddition:rolling/gold_ingot recipe (createaddition:rolling/gold_ingot) specified a duration. Durations have no impact on this type of recipe.
[15:34:14] [Worker-Main-1/WARN]: Your custom createaddition:rolling/straw recipe (createaddition:rolling/straw) specified a duration. Durations have no impact on this type of recipe.
[15:34:14] [Worker-Main-1/WARN]: Your custom createaddition:charging/weathered_copper recipe (createaddition:charging/weathered_copper) specified a duration. Durations have no impact on this type of recipe.
[15:34:14] [Worker-Main-1/WARN]: Your custom createaddition:charging/exposed_copper_shingle_stairs recipe (createaddition:charging/exposed_copper_shingle_stairs) specified a duration. Durations have no impact on this type of recipe.
[15:34:14] [Worker-Main-1/WARN]: Your custom createaddition:charging/cut_copper_block recipe (createaddition:charging/cut_copper_block) specified a duration. Durations have no impact on this type of recipe.
[15:34:14] [Worker-Main-1/WARN]: Your custom createaddition:charging/channeling recipe (createaddition:charging/channeling) specified a duration. Durations have no impact on this type of recipe.
[15:34:14] [Worker-Main-1/WARN]: Your custom createaddition:charging/cut_copper_slab recipe (createaddition:charging/cut_copper_slab) specified a duration. Durations have no impact on this type of recipe.
[15:34:14] [Worker-Main-1/WARN]: Your custom createaddition:charging/weathered_cut_copper_stairs recipe (createaddition:charging/weathered_cut_copper_stairs) specified a duration. Durations have no impact on this type of recipe.
[15:34:14] [Worker-Main-1/ERROR]: Parsing error loading recipe createaddition:compat/immersiveengineering/item_application/leaded_concrete
com.google.gson.JsonSyntaxException: Unknown item 'immersiveengineering:concrete'
	at net.minecraft.class_1869.method_17878(class_1869.java:272) ~[server-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_1869.method_8155(class_1869.java:272) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8107(class_1856.java:160) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_52177(class_1856.java:135) ~[server-intermediary.jar:?]
	at com.simibubi.create.content.processing.recipe.ProcessingRecipeSerializer.readFromJson(ProcessingRecipeSerializer.java:66) ~[create-fabric-0.5.1-f-build.1417+mc1.20.1.jar:?]
	at com.simibubi.create.content.processing.recipe.ProcessingRecipeSerializer.fromJson(ProcessingRecipeSerializer.java:154) ~[create-fabric-0.5.1-f-build.1417+mc1.20.1.jar:?]
	at com.simibubi.create.content.processing.recipe.ProcessingRecipeSerializer.method_8121(ProcessingRecipeSerializer.java:21) ~[create-fabric-0.5.1-f-build.1417+mc1.20.1.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[server-intermediary.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:68) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[server-intermediary.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:68) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[server-intermediary.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:68) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179) ~[?:?]
	at net.minecraft.class_4014$1.method_18374(class_4014.java:51) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[server-intermediary.jar:?]
	at net.minecraft.class_4014$1.method_18352(class_4014.java:48) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
[15:34:14] [Worker-Main-1/WARN]: Your custom createaddition:charging/exposed_cut_copper_stairs recipe (createaddition:charging/exposed_cut_copper_stairs) specified a duration. Durations have no impact on this type of recipe.
[15:34:14] [Worker-Main-1/WARN]: Your custom createaddition:rolling/electrum_plate recipe (createaddition:rolling/electrum_plate) specified a duration. Durations have no impact on this type of recipe.
[15:34:14] [Worker-Main-1/WARN]: Your custom createaddition:charging/exposed_copper_shingles recipe (createaddition:charging/exposed_copper_shingles) specified a duration. Durations have no impact on this type of recipe.
[15:34:14] [Worker-Main-1/WARN]: Your custom createaddition:charging/weathered_cut_copper recipe (createaddition:charging/weathered_cut_copper) specified a duration. Durations have no impact on this type of recipe.
[15:34:14] [Worker-Main-1/WARN]: Your custom createaddition:charging/cut_copper_stairs recipe (createaddition:charging/cut_copper_stairs) specified a duration. Durations have no impact on this type of recipe.
[15:34:14] [Worker-Main-1/WARN]: Your custom createaddition:charging/copper_shingle_slab recipe (createaddition:charging/copper_shingle_slab) specified a duration. Durations have no impact on this type of recipe.
[15:34:14] [Worker-Main-1/WARN]: Your custom createaddition:charging/weathered_cut_copper_slab recipe (createaddition:charging/weathered_cut_copper_slab) specified a duration. Durations have no impact on this type of recipe.
[15:34:14] [Worker-Main-1/WARN]: Your custom createaddition:rolling/copper_plate recipe (createaddition:rolling/copper_plate) specified a duration. Durations have no impact on this type of recipe.
[15:34:14] [Worker-Main-1/WARN]: Your custom createaddition:rolling/iron_plate recipe (createaddition:rolling/iron_plate) specified a duration. Durations have no impact on this type of recipe.
[15:34:14] [Worker-Main-1/WARN]: Your custom createaddition:charging/weathered_copper_shingle_slab recipe (createaddition:charging/weathered_copper_shingle_slab) specified a duration. Durations have no impact on this type of recipe.
[15:34:14] [Worker-Main-1/WARN]: Your custom createaddition:charging/exposed_copper_shingle_slab recipe (createaddition:charging/exposed_copper_shingle_slab) specified a duration. Durations have no impact on this type of recipe.
[15:34:14] [Worker-Main-1/WARN]: Your custom createaddition:rolling/gold_plate recipe (createaddition:rolling/gold_plate) specified a duration. Durations have no impact on this type of recipe.
[15:34:14] [Worker-Main-1/INFO]: Loaded 43 recipes
[15:34:14] [Worker-Main-1/INFO]: Loaded 3819 advancements
[15:34:14] [Thread-13/INFO]: Loaded 20 translation keys
```

**To Reproduce**
Errors when starting and shutting down the server

**Additional context**
- Mod version: createaddition-fabric+1.20.1-1.2.4

- Fabric version: fabric-api-0.92.2+1.20.1
- Create version:create-fabric-0.5.1-f-build.1417+mc1.20.1

**Comment by Abadima** [comment]
I 2nd this

**Comment by mrganimurat** [comment]
Hello, you still haven't found the answer to fix this? If you found it, can you tell me about it?

**Comment by swe3per** [comment]
> Hello, you still haven't found the answer to fix this? If you found it, can you tell me about it?

It should be that createaddition include recipes of other modules, such as immersiveengineering, but because I did not install the corresponding mod, some items in the recipe were not registered. This is a normal prompt and does not affect the game at all.
